config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :incomes
  devise_for :usuarios
  root to: "sites#index"

  get '/incomes',to:'incomes#index'

  get '/index2',to:'sites#index2' # ruta de ensayo

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/income.rb
class Income < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_usuario!

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ show edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1 or /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully created." }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "Expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:date, :amount, :category, :glosa)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: %i[ show edit update destroy ]

  # GET /incomes or /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1 or /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes or /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to income_url(@income), notice: "Income was successfully created." }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1 or /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to income_url(@income), notice: "Income was successfully updated." }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1 or /incomes/1.json
  def destroy
    @income.destroy

    respond_to do |format|
      format.html { redirect_to incomes_url, notice: "Income was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def income_params
      params.require(:income).permit(:date, :amount, :category, :glosa)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :glosa %>
    <%= form.text_field :glosa %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<div class="col-auto p-5 text-center">

<p id="notice"><%= notice %></p>

<h1>Egresos</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Category</th>
      <th>Glosa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.date %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.category %></td>
        <td><%= expense.glosa %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %> <br><br>

<%= link_to "Salir", :back %>
</div>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expense.category %>
</p>

<p>
  <strong>Glosa:</strong>
  <%= @expense.glosa %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/incomes/_form.html.erb
<%= form_with(model: income) do |form| %>
  <% if income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :glosa %>
    <%= form.text_field :glosa %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<div class="col-auto p-5 text-center">
<p id="notice"><%= notice %></p>

<h1>Ingresos</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>monto</th>
      <th>Categoria</th>
      <th>Glosa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.date %></td>
        <td><%= income.amount %></td>
        <td><%= income.category %></td>
        <td><%= income.glosa %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ingreso nuevo', new_income_path %> <br><br>

<%= link_to "Salir", :back %>
</div>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @income.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @income.category %>
</p>

<p>
  <strong>Glosa:</strong>
  <%= @income.glosa %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="UTF-8">
    <title>MisfinanzasRuizAbraham</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/sites/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible"
   content="IE=edge">
    <title>MisfinanzasRuizAbraham</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


  </head>

  <body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

  <header>
    <nav class="navbar navbar-expand-lg navbar-warning bg-warning">
      <div class="container-fluid">
            <a class="navbar-brand" href="#"> <b>Mis Finanzas</b> </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/"><b>Inicio</b></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="/usuarios/sign_up"><b>Registrarse</b></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="/usuarios/sign_in"><b>Ingresar</b></a>
                </li>
              </ul>
            </div>
            <span class="navbar-text">
              Bienvenido a la nueva forma de ordenar tus Finanzas
              </span>
        </div>
     </nav>
    </header>

        <div class="container">
          <div class="row">
             <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">

             </div>
          </div>
          <h1>¡Ten el control de tus gastos e ingresos hoy!</h1>
        </div>

    <!-- Librería jQuery requerida por los plugins de JavaScript -->
    <script src="http://code.jquery.com/jquery.js"></script>

    <!-- Todos los plugins JavaScript de Bootstrap (también puedes
         incluir archivos JavaScript individuales de los únicos
         plugins que utilices) -->
    <script src="js/bootstrap.min.js"></script>


  <% if usuario_signed_in? then %>
  <B>Bienvenido  <%= current_usuario&.email %></B><br/>
  <div class="col-auto p-5 text-center">


                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="/incomes"> <h1> <b>Ingresos</b></h1></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="/expenses"><h1><b>Egresos</b></h1></a>
                </li>




  <%= link_to "Salir", :destroy_usuario_session, method: :delete %>
<% else %>
  <%= link_to "Ingresar", :new_usuario_session %>
<% end %>
 </div>
<%= yield %>

  </body>
</html>

app/views/sites/index2.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>

    <!--Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-warning bg-warning">
      <div class="container-fluid">
            <a class="navbar-brand" href="#">Mis Finanzas</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Registrarse</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Ingresar</a>
                </li>
              </ul>
              <span class="navbar-text">
              Bienvenido a la nueva forma de ordenar tus Finanzas
              </span>
            </div>
        </div>
     </nav>
    </header>

        <div class="container">
          <div class="row">
             <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">

             </div>
          </div>
          <h1>¡Ten el control de tus gastos e ingresos hoy!</h1>
        </div>

    <!-- Librería jQuery requerida por los plugins de JavaScript -->
    <script src="http://code.jquery.com/jquery.js"></script>

    <!-- Todos los plugins JavaScript de Bootstrap (también puedes
         incluir archivos JavaScript individuales de los únicos
         plugins que utilices) -->
    <script src="js/bootstrap.min.js"></script>


  <% if usuario_signed_in? then %>
  <B>Bienvenido  <%= current_usuario&.email %></B><br/>
  <%= link_to "Salir", :destroy_usuario_session, method: :delete %>
<% else %>
  <%= link_to "Ingresar", :new_usuario_session %>
<% end %>
<%= yield %>

  </body>
</html>